//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UZPIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Доставка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Доставка()
        {
            this.Товарная_накладная = new HashSet<Товарная_накладная>();
        }
    
        public int Код_доставки { get; set; }
        public int Код_заказа { get; set; }
        public System.DateTime Дата { get; set; }
        public string Адрес { get; set; }
        public decimal Стоимость { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Товарная_накладная> Товарная_накладная { get; set; }
    }
}
