//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UZPIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.Состав_Накладной = new HashSet<Состав_Накладной>();
            this.Товары_на_заказ = new HashSet<Товары_на_заказ>();
        }
    
        public int Код_товара { get; set; }
        public int Код_вида_товара { get; set; }
        public string Наименование { get; set; }
        public string Описание { get; set; }
        public string Срок_годности { get; set; }
        public decimal Цена { get; set; }
    
        public virtual Вид_товара Вид_товара { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_Накладной> Состав_Накладной { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Товары_на_заказ> Товары_на_заказ { get; set; }
    }
}
