//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UZPIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары_на_заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары_на_заказ()
        {
            this.Партии = new HashSet<Партии>();
        }
    
        public int Код_ТНЗ { get; set; }
        public int Код_товара { get; set; }
        public int Код_заказа { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Партии> Партии { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
