//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UZPIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товарная_накладная
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товарная_накладная()
        {
            this.Состав_Накладной = new HashSet<Состав_Накладной>();
        }
    
        public int Код_ТН { get; set; }
        public int Код_доставки { get; set; }
    
        public virtual Доставка Доставка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_Накладной> Состав_Накладной { get; set; }
    }
}
